/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiResumeChatRouteImport } from './routes/api.resume-chat'
import { Route as ApiDownloadCvRouteImport } from './routes/api.download-cv'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeChatRoute = ApiResumeChatRouteImport.update({
  id: '/api/resume-chat',
  path: '/api/resume-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadCvRoute = ApiDownloadCvRouteImport.update({
  id: '/api/download-cv',
  path: '/api/download-cv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/download-cv': typeof ApiDownloadCvRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/download-cv': typeof ApiDownloadCvRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/download-cv': typeof ApiDownloadCvRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/download-cv' | '/api/resume-chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/download-cv' | '/api/resume-chat'
  id: '__root__' | '/' | '/api/download-cv' | '/api/resume-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDownloadCvRoute: typeof ApiDownloadCvRoute
  ApiResumeChatRoute: typeof ApiResumeChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-chat': {
      id: '/api/resume-chat'
      path: '/api/resume-chat'
      fullPath: '/api/resume-chat'
      preLoaderRoute: typeof ApiResumeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-cv': {
      id: '/api/download-cv'
      path: '/api/download-cv'
      fullPath: '/api/download-cv'
      preLoaderRoute: typeof ApiDownloadCvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDownloadCvRoute: ApiDownloadCvRoute,
  ApiResumeChatRoute: ApiResumeChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
